Repository pycontribs/subprocess-tee, pull requests merged in 2021-04, with the labels that each got.

#28 Increase asyncio.create_subprocess_shell limit
  lib/subprocess_tee/__init__.py
Labels: bug

#27 There is no need for a 'rich' extra
  setup.cfg
Labels: bug

#29 Rename lib to src
  .pre-commit-config.yaml
  setup.cfg
  src/subprocess_tee/__init__.py
  src/subprocess_tee/py.typed
  src/subprocess_tee/test/__init__.py
  src/subprocess_tee/test/test_rich.py
  src/subprocess_tee/test/test_unit.py
Labels: skip-changelog

#30 Bump linters
  .pre-commit-config.yaml
Labels: skip-changelog

#31 Assure check=True is supported
  src/subprocess_tee/__init__.py
  src/subprocess_tee/test/test_unit.py
  tox.ini
Labels: bug

#32 Create FUNDING.yml
  .github/FUNDING.yml
Labels: skip-changelog

#33 Keep devnull use compatible with subprocess.run
  src/subprocess_tee/__init__.py
Labels: bug

#34 Assure check with success does not raise
  src/subprocess_tee/__init__.py
  src/subprocess_tee/test/test_unit.py
  tox.ini
Labels: bug

#35 Assure returned stderr matches one from subprocess.run
  src/subprocess_tee/__init__.py
  src/subprocess_tee/test/test_unit.py
Labels: bug

#36 Pin test dependencies
  Dockerfile
  setup.cfg
  test-requirements.in
  test-requirements.txt
  tox.ini
Labels: skip-changelog

#37 Add tee optional argument
  README.md
  src/subprocess_tee/__init__.py
Labels: enhancement
