Repository pycontribs/subprocess-tee, pull requests merged in 2022-11, with the labels that each got.

#63 Update alpine image
  Dockerfile
Labels: skip-changelog

#62 Remove mock from project's test requirements
  setup.cfg
Labels: skip-changelog

#64 Mark test test_rich_console_ex as broken
  src/subprocess_tee/test/test_rich.py
  tox.ini
Labels: bug

#65 Remove support for py36
  .github/workflows/tox.yml
  setup.cfg
Labels: bug

#66 Update GHA
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .github/workflows/labels.yml
  .github/workflows/push.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/tox.yml
Labels: skip-changelog

#70 Remove support for py37
  .github/workflows/tox.yml
  setup.cfg
Labels: skip-changelog

#71 Update GHA
  .github/workflows/tox.yml
Labels: skip-changelog

#72 Enable support for py311
  .github/workflows/tox.yml
  setup.cfg
Labels: skip-changelog

#76 Migrate packaging to pyproject.toml
  .flake8
  .pre-commit-config.yaml
  MANIFEST.in
  pyproject.toml
  setup.cfg
  setup.py
  src/subprocess_tee/__init__.py
  src/subprocess_tee/test/test_unit.py
  tox.ini
Labels: enhancement, skip-changelog

#77 Move tests outside the library
  test/__init__.py
  test/test_func.py
  test/test_rich.py
  test/test_unit.py
Labels: bug, skip-changelog

#80 Clear build dependencies
  .pre-commit-config.yaml
  pyproject.toml
  src/subprocess_tee/__init__.py
Labels: bug

#82 Add "setuptools >= 61.0" to build system requires
  pyproject.toml
  tox.ini
Labels: bug

#81 Configure packit
  .config/subprocess-tee.spec
  .gitignore
  .packit.yaml
Labels: bug
