Repository pycontribs/subprocess-tee, pull requests merged in 2024-12, with the labels that each got.

#140 Remove support for python 3.9
  .github/workflows/release.yml
  .github/workflows/tox.yml
  pyproject.toml
Labels: major

#135 Fix a typo in a test docstring - "Valida" > "Validate"
  test/test_unit.py
Labels: bug

#139 Update GHA jobs
  .github/workflows/tox.yml
  pyproject.toml
  tox.ini
Labels: skip-changelog

#141 Expose support for python 3.13
  pyproject.toml
Labels: bug

#143 Enable ruff
  .pre-commit-config.yaml
  pyproject.toml
  src/subprocess_tee/__init__.py
  test/test_func.py
  test/test_rich.py
  test/test_unit.py
Labels: bug

#136 Use public pytest interface for importing CaptureFixture
  test/test_unit.py
Labels: skip-changelog

#137 Make `test_run_string` pass when the default shell is not bash
  test/test_unit.py
Labels: skip-changelog

#144 Remove use of flake8
  .flake8
  .pre-commit-config.yaml
  tox.ini
Labels: skip-changelog

#145 Upgrade linters
  .config/constraints.txt
  .config/dictionary.txt
  .config/requirements-docs.in
  .config/requirements-lock.txt
  .config/requirements-test.in
  .config/requirements.in
  .github/dependabot.yml
  .gitignore
  .packit.yaml
  .pre-commit-config.yaml
  .prettierignore
  .prettierrc.yaml
  .taplo.toml
  Dockerfile
  README.md
  cspell.config.yaml
  mkdocs.yml
  pyproject.toml
  src/subprocess_tee/__init__.py
  test/__init__.py
  test/test_rich.py
  test/test_unit.py
  tox.ini
Labels: skip-changelog

#147 Fix project description
  pyproject.toml
Labels: bug

#149 Add types to run command
  .config/constraints.txt
  .pre-commit-config.yaml
  pyproject.toml
  src/subprocess_tee/__init__.py
  src/subprocess_tee/_types.py
  test/test_unit.py
  tox.ini
Labels: bug
